---
# tasks file for qgis

- name: Create keyring directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Add qgis repository keyring
  ansible.builtin.get_url:
    url: "{{ qgis_keyring_url }}"
    dest: /etc/apt/keyrings/qgis-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add qgis repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] {{ qgis_repo_url }} {{ ansible_distribution_release }} main
    state: present

- name: Install qgis packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - qgis
      - grass=7.8.2-1build3 # rewquirement for qgis-plugin-grass
      - python-qgis
      - qgis-plugin-grass
...