---
- name: Add ubuntugis repository
  ansible.builtin.apt_repository:
    repo: 'ppa:ubuntugis/ppa'
    state: present

- name: Install packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - gdal-bin
      - git
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - python3-gdal
...