---
- name: Add ubuntugis repository
  ansible.builtin.apt_repository:
    repo: deb https://ubuntugis.qgis.org/ubuntugis {{ ansible_distribution_release }} main
    state: present

- name: Install packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - gdal-bin
      - git
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - python3-gdal
...