---
- name: Create keyring directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Add qgis repository keyring
  ansible.builtin.get_url:
    url: "{{ qgis_keyring_url }}"
    dest: /etc/apt/keyrings/qgis-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add ubuntugis repository
  ansible.builtin.apt_repository:
    repo: deb https://ubuntugis.qgis.org/ubuntugis [signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] {{ ansible_distribution_release }} main
    state: present

- name: Install packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - gdal-bin
      - git
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - python3-gdal
...